// Pure Kotlin/JVM module: no Android dependency, so `./gradlew :core:test` runs on any JDK 17.
plugins {
    alias(libs.plugins.kotlin.jvm)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    // ai.onnxruntime + org.json APIs: compiled against, NOT bundled. On Android the app supplies
    // onnxruntime-android (same ai.onnxruntime API) and the platform's org.json; the JVM tests
    // supply the desktop onnxruntime and org.json.
    compileOnly(libs.onnxruntime.jvm)
    compileOnly(libs.org.json)
    testImplementation(libs.junit)
    testImplementation(libs.org.json)
    testImplementation(libs.onnxruntime.jvm)
    testImplementation(libs.kotlinx.coroutines.test)
}

tasks.test {
    // golden vectors generated by the Python reference live in the monorepo
    systemProperty("sih26168.repoRoot", rootProject.projectDir.parentFile.absolutePath)
}
