// Pure Kotlin/JVM module: no Android dependency, so `./gradlew :core:test` runs on any JDK 17.
plugins {
    alias(libs.plugins.kotlin.jvm)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    testImplementation(libs.junit)
    testImplementation(libs.org.json)
    testImplementation(libs.kotlinx.coroutines.test)
}

tasks.test {
    // golden vectors generated by the Python reference live in the monorepo
    systemProperty("sih26168.repoRoot", rootProject.projectDir.parentFile.absolutePath)
}
